name: babyai
description: BabyAI mobile app
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_svg: ^2.0.17
  flutter_markdown: ^0.7.6+2
  markdown: ^7.3.0
  speech_to_text: ^7.0.0
  image_picker: ^1.1.2
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/app_logo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Variable.ttf
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Variable.ttf
